name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: self-hosted

    env:
      DOTNET_ROOT: ${{ github.workspace }}/.dotnet
      PATH: ${{ github.workspace }}/.dotnet:$PATH:/usr/bin:/home/runner/.dotnet/tools
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore Pazar/Pazar.sln

      - name: Build project
        run: dotnet build --no-restore --configuration Release Pazar/Pazar.sln

      - name: Install dotCover
        run: dotnet tool install --global JetBrains.dotCover.GlobalTool

      - name: Prepare SonarQube Scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:$HOME/.dotnet/tools"

      - name: Run SonarQube Scan Begin
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner begin /k:"Pazar" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths="${{ github.workspace }}/coverage/dotCover.Output.html"

      - name: Build project for SonarQube
        run: dotnet build --no-incremental Pazar/Pazar.sln

      - name: Run tests with coverage
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          mkdir -p ${{ github.workspace }}/coverage
          dotnet dotcover test Pazar/Pazar.sln --dcReportType=HTML --output="${{ github.workspace }}/coverage/dotCover.Output.html"

      - name: Run SonarQube Scan End
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ${{ github.workspace }}/coverage/dotCover.Output.html
