name: SonarScanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: self-hosted

    env:
      DOTNET_ROOT: ${{ github.workspace }}/.dotnet
      PATH: ${{ github.workspace }}/.dotnet:$PATH:/usr/bin:/home/runner/.dotnet/tools:/usr/lib/jvm/java-17-openjdk-amd64/bin
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore Pazar/Pazar.sln

      - name: Build project
        run: dotnet build --no-restore --configuration Release Pazar/Pazar.sln

      - name: Run tests
        run: dotnet test --no-build --configuration Release Pazar/Pazar.sln

      - name: Prepare SonarQube Scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet tool install --global JetBrains.dotCover.GlobalTool

      - name: Run SonarQube Scan
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet sonarscanner begin /k:"Pazar" /d:sonar.host.url="$SONAR_HOST_URL" /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.dotcover.reportsPaths="${{ github.workspace }}/coverage/dotCover.Output.html"
          dotnet build Pazar/Pazar.sln
          mkdir -p ${{ github.workspace }}/coverage
          cd Pazar
          dotnet dotcover test --dcReportType=HTML --output="${{ github.workspace }}/coverage/dotCover.Output.html"
          cd ..
          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
